[platformio]
default_envs = esp32s3_knob
build_cache_dir = D:\.platformio\.cache

[env:esp32s3_knob]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_build.partitions = partitions.csv
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi

monitor_speed = 115200
upload_speed = 921600
upload_port = COM3
monitor_port = COM3

build_unflags =
    -D ARDUINO_USB_MODE=1

build_flags =
    -DLV_CONF_INCLUDE_SIMPLE
    -I include
    -D BOARD_HAS_PSRAM
    -D ARDUINO_USB_MODE=0
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D CORE_DEBUG_LEVEL=1

lib_deps =
    lvgl/lvgl@^8.3.11
    adafruit/Adafruit NeoPixel@^1.12.3
    bblanchon/ArduinoJson@^7.2.0
